//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookingcombo
    {
        public Nullable<int> booking_id { get; set; }
        public Nullable<int> combo_id { get; set; }
        public int bookingcombo_id { get; set; }
        public Nullable<int> quantity_combo { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual FoodDrink FoodDrink { get; set; }
    }
}
