//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int booking_id { get; set; }
        public Nullable<int> showtime_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string number_of_seats { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public Nullable<System.DateTime> booking_time { get; set; }
        public string combo { get; set; }
    
        public virtual Showtime Showtime { get; set; }
    }
}
