//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chair
    {
        public int chair_id { get; set; }
        public int room_id { get; set; }
        public string name_chair { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
