//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodDrink
    {
        public int fooddrink_id { get; set; }
        public string fooddrink_name { get; set; }
        public string fooddrink_description { get; set; }
        public Nullable<int> fooddrink_status { get; set; }
        public Nullable<decimal> price { get; set; }
    }
}
