//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketBooking.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MovieTicketBookingEntities2 : DbContext
    {
        public MovieTicketBookingEntities2()
            : base("name=MovieTicketBookingEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Bookingcombo> Bookingcomboes { get; set; }
        public virtual DbSet<Bookingseat> Bookingseats { get; set; }
        public virtual DbSet<Chair> Chairs { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<FoodDrink> FoodDrinks { get; set; }
        public virtual DbSet<Movie> Movies { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Showtime> Showtimes { get; set; }
        public virtual DbSet<Theater> Theaters { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
