//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string email { get; set; }
        public string user_phone { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<int> gender { get; set; }
        public string password { get; set; }
    }
}
